# Generated by Django 5.2.3 on 2025-07-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blogcategory_blogpost'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='solo_miembros',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text=' El grupo al que pertenece este usuario. El usuario obtendra todos  los permisos que le brinde cada uno de sus grupos.', related_name='usuario_personalizado_set', related_query_name='usuario_personalizado', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos especificos para este usuario.', related_name='usuario_personalizado_set', related_query_name='usuario_personalizado', to='auth.permission', verbose_name='user permisos de usuario'),
        ),
    ]
