# Generated by Django 5.0.6 on 2025-08-08 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blogpost_solo_miembros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.producto'),
        ),
    ]
