# Generated by Django 5.0.6 on 2025-08-08 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_imagenproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resena',
        ),
    ]
