# Generated by Django 5.2.3 on 2025-08-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='api.producto'),
        ),
    ]
