# Generated by Django 5.0.6 on 2025-08-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_resena_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo_membresia',
            field=models.CharField(choices=[('regular', 'Usuario regular'), ('premium', 'Usuario Premium')], default='regular', max_length=20),
        ),
    ]
