# Generated by Django 5.0.6 on 2025-08-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_usuariopersonalizado_tipo_membresia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='edad_recomendada',
        ),
        migrations.AddField(
            model_name='producto',
            name='edad_recomendada_max',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='producto',
            name='edad_recomendada_min',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
