# Generated by Django 5.0.6 on 2025-08-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_producto_edad_recomendada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='edad_recomendada_max',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='edad_recomendada_min',
            field=models.PositiveIntegerField(),
        ),
    ]
