# Generated by Django 5.2.3 on 2025-08-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_producto_edad_recomendada_max_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='ciudad_envio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='codigo_postal_envio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='direccion_envio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='nombre_envio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='telefono_envio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='El grupo al que pertenece este usuario. El usuario obtendrá todos los permisos que le brinde cada uno de sus grupos.', related_name='usuario_personalizado_set', related_query_name='usuario_personalizado', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuario_personalizado_set', related_query_name='usuario_personalizado', to='auth.permission', verbose_name='user permisos de usuario'),
        ),
    ]
