# Generated by Django 5.2.3 on 2025-08-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comentarios',
        ),
    ]
