# Generated by Django 5.2.3 on 2025-08-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_comment_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='content',
            new_name='contenido',
        ),
    ]
