# Generated by Django 5.0.6 on 2025-08-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_producto_options_calificacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calificacion',
        ),
    ]
