# Generated by Django 5.0.6 on 2025-08-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
