# Generated by Django 5.2.3 on 2025-08-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_itemorden_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/blog/'),
        ),
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(upload_to='media/productos/'),
        ),
    ]
